### ISSUE TITLE
Call to undefined method WP_Image_Editor_Imagick::get_error_message()

### ISSUE THREAD

**Issue by cdukes** [deliciousbrains/wp-image-processing-queue#10]
Running includes/class-ipq-process.php:75 triggers `PHP Fatal error:  Uncaught Error: Call to undefined method WP_Image_Editor_Imagick::get_error_message()`

I think you mean to get the message from a WP_Error object, but you're not saving one during the resize. Something like this should work:

```
$result = $editor->resize( $width, $height, $crop );
if ( is_wp_error( $result ) ) {
	throw new IPQ_Process_Exception( 'Error resizing image: ' . $result->get_error_message() );
}
```

**Comment by A5hleyRich** [comment]
Thanks!

Resolved in 5527baa695e27b9bfddbcc310a43d699baa7e773
