### ISSUE TITLE
WP_Background_Process

### ISSUE THREAD

**Issue by tomusborne** [deliciousbrains/wp-image-processing-queue#12]
`image-processing-queue.php` makes reference to a `vendor` folder, which doesn't seem to exist in this repo.

Do we need to include another library in order for this one to work? I've noticed the WP.org repo has the vendor folder.

Thanks!

**Comment by A5hleyRich** [comment]
If you're including this as part of a theme or plugin you need to run `composer install`

https://github.com/deliciousbrains/wp-image-processing-queue#install-as-a-theme-library

**Comment by tomusborne** [comment]
Reading instructions FTW. Thank you!
