### ISSUE TITLE
Detect if job already exists

### ISSUE THREAD

**Issue by A5hleyRich** [deliciousbrains/wp-image-processing-queue#3]
It's possible to push multiple background jobs to the queue for the same image. We need to check if the image already has a background job outstanding before pushing another to the queue.

**Comment by bleepsandblops** [comment]
Yes that would be amazing, on some of my busy sites the wp_options table ends up filling up and doesn't clear up.

**Comment by A5hleyRich** [comment]
A locking mechanism has been introduced in the latest version to prevent multiple queue jobs being created. Also migrated to using [WP Queue](https://github.com/A5hleyRich/wp-queue).
