### ISSUE TITLE
Add template function for retrieving url of the desired image size

### ISSUE THREAD

**Issue by OriginalEXE** [deliciousbrains/wp-image-processing-queue#5]
Hello,

first of all, this looks awesome. My question is, have you thought about providing a template function that would return only the url of the specified image size? It could for example return the full-size image url if the desired size is not yet available, or if the image is not big enough to satisfy the size request.

Thanks

**Comment by TMcLoone** [comment]
+1 on this. Would love to be able to work with each url rather than just output the entire image. (Especially useful for background images)

**Comment by A5hleyRich** [comment]
This has been added in https://github.com/deliciousbrains/wp-image-processing-queue/commit/bfbc9d46c6673d035ed992a93c320e99c7851e5c. If the image size doesn't exist the full size is returned and the requested size is generated in the background.

Any feedback would be appreciated. 👍

**Comment by sectsect** [comment]
@A5hleyRich 

Thanks for great work :tada:
Can you update the version tag for Composer?
