### ISSUE TITLE
working locally?

### ISSUE THREAD

**Issue by Kateriine** [deliciousbrains/wp-image-processing-queue#6]
Hello,

Installed your (probably) awesome and (certainly) needed work locally, but it seems not to work here... No error, the tag is displayed on the template, but the image is not resized and the src link is still the full image (also, the image sizes meta have not been updated). 
`<img width="317" height="400" src="https://test.dev/wp-content/uploads/2015/05/17353604_1490626997627722_8477959042079393974_n.jpg" class="header-banner" alt="">`
Checked the permissions on wp-content/uploads, which are ok, and the add_image_size is working. I think for some reason, task() in IPQ_Process() is not triggered, but I don't know why...

**Comment by pixeltherapy** [comment]
Hey, I just integrated this into my theme locally and it works fine. I think the problem might be that you have installed the plugin without adding anything to your theme to use it. This fact is implied rather than stated in the readme.

Once added either as a plugin or integrated into your theme, you would call an image using ```ipq_get_theme_image()``` instead of ```wp_get_attachment_image()```.

I might have the wrong end of the stick here so let me know.

**Comment by Kateriine** [comment]
Hello,

Thanks for answering. Actually I added it directly in the theme with composer, and I tested it with ipq_get_image() as needed; I also changed the theme and deactivated the plugins, nothing better... maybe something wrong with my computer? 
Anyway, I tested it on another site and it worked perfectly there, so too bad for the first one, the 2nd one is lucky ^^

**Comment by A5hleyRich** [comment]
Is the site able to resolve itself? https://deliciousbrains.com/wp-offload-s3/doc/background-processes-not-completing/#hostname

**Comment by Kateriine** [comment]
Well, doesn't change anything :/
But don't worry about it, it's not that bad, I'll figure something else :)

**Comment by Kateriine** [comment]
I was wondering... Maybe it's because WP is in a subfolder?

**Comment by jacobdubail** [comment]
Similar issue here running a local dev site with Local by Flywheel. The image size is never generated. I don't see any network requests to the admin-ajax url. No errors on the page. Plugin is included in the theme and the files are required. ran composer install without issue. All of the files are loading correctly. The site isn't accessible on the internet, so the hostname won't resolve anywhere. Ideas? Thanks!

**Comment by A5hleyRich** [comment]
This should be a non-issue now that we've moved to using [WP Queue](https://github.com/A5hleyRich/wp-queue), which piggybacks onto WP cron.
