### ISSUE TITLE
Update .org Plugin Repo Version?

### ISSUE THREAD

**Issue by leepeterson** [deliciousbrains/wp-image-processing-queue#8]
@A5hleyRich Any chance you will be pushing v0.2 which contains the much-needed [ipq_get_theme_image_url](https://github.com/deliciousbrains/wp-image-processing-queue/blob/master/includes/ipq-template-functions.php#L29-L43) to the plugin repo soon-ish? Just curious. Trying to plan out plugin sources and such.

**Comment by A5hleyRich** [comment]
Done!
